In [1]:
import tensorflow as tf
import os
from os.path import isfile, join
import numpy as np
import shutil
from tensorflow import keras
from pathlib import Path
from IPython.display import display, Audio
import subprocess

In [2]:
def create_folder(folder_name):
    os.makedirs(folder_name, exist_ok=True)

In [3]:
import sounddevice as sd
import wave

def record_audio(duration, sample_rate, channels, filename):
    # Record audio from the microphone
    recording = sd.rec(int(duration * sample_rate), samplerate=sample_rate, channels=channels)
    sd.wait()

    # Convert audio data to 16-bit integers
    audio_data = (recording * (2 ** 15)).astype('int16')

    # Save audio data to WAV file
    with wave.open(filename, 'wb') as file:
        file.setnchannels(channels)
        file.setsampwidth(2)
        file.setframerate(sample_rate)
        file.writeframes(audio_data.tobytes())

In [4]:
x=1
while(x):
    folder=input('ENTER SPEAKER NAME')
    # Example usage
    folder_name = "custome_audio/audio/"+folder
    create_folder(folder_name)
    print('read it:\nIndia is a country renowned for its incredible richness in various aspects. One of the key factors contributing to Indias richness is its unparalleled cultural diversity. With a plethora of languages, religions, traditions, and festivals, India is a vibrant tapestry of different cultural threads. From the snowy peaks of the Himalayas to the sun-kissed beaches of Goa, the countrys geographical diversity further enhances its richness.Indias historical significance adds another layer to its richness. It has been a land of ancient civilizations, dynasties, and empires, leaving behind a legacy of awe-inspiring monuments, palaces, temples, and forts. The Taj Mahal, an epitome of architectural brilliance, stands as a symbol of Indias cultural and historical grandeur.Spirituality and philosophy have thrived in India for centuries. The birthplace of religions like Hinduism, Buddhism, Jainism, and Sikhism, India has been a sanctuary for seekers of spiritual enlightenment. Ashrams, pilgrimage sites, and practices like yoga and meditation attract people from all over the world, seeking solace and inner awakening.Art and handicrafts showcase Indias creativity and artistic finesse. From intricate paintings to mesmerizing sculptures, traditional music and dance forms to hand-woven textiles, Indian art forms are a testament to the countrys rich artistic heritage. The skills and craftsmanship of Indian artisans are celebrated globally.Indias biodiversity and natural beauty are extraordinary. Vast stretches of lush forests, majestic mountains, pristine rivers, and diverse wildlife make India a paradise for nature lovers. National parks and wildlife sanctuaries preserve the countrys ecological treasures, reflecting its commitment to conservation.The culinary delights of India are a treat for the taste buds. Indian cuisine, with its myriad flavors, spices, and regional specialties, showcases the countrys gastronomic richness. From aromatic biryanis to spicy curries, from delectable sweets to street food, Indian cuisine is a delightful journey of flavors.Indias traditional practices, such as Ayurveda, yoga, astrology, and traditional farming methods, add to its richness. These ancient knowledge systems have been passed down through generations, contributing to the well-being and sustainability of society.In summary, Indias richness lies in its cultural diversity, historical significance, architectural marvels, spiritual traditions, artistic brilliance, natural beauty, culinary treasures, and traditional practices. This vibrant and multifaceted nation offers a captivating experience for those seeking to explore its richness and immerse themselves in its diverse tapestry of traditions and heritage.')
    for i in range(100):
        # Example usage
        duration = 2  # Duration of audio recording in seconds
        sample_rate = 44100  # Sample rate of audio recording
        channels = 2  # Number of audio channels (1 for mono, 2 for stereo)
        filename = "custome_audio/audio/"+folder+'/'+folder+str(i+1)+'.wav'  # Output file name

        # Record audio from the microphone and save it as a WAV file
        record_audio(duration, sample_rate, channels, filename)
    x=int(input('DO U WANT TO CONTINUE ? (1/0)'))

ENTER SPEAKER NAMEBhavani1
read it:
India is a country renowned for its incredible richness in various aspects. One of the key factors contributing to Indias richness is its unparalleled cultural diversity. With a plethora of languages, religions, traditions, and festivals, India is a vibrant tapestry of different cultural threads. From the snowy peaks of the Himalayas to the sun-kissed beaches of Goa, the countrys geographical diversity further enhances its richness.Indias historical significance adds another layer to its richness. It has been a land of ancient civilizations, dynasties, and empires, leaving behind a legacy of awe-inspiring monuments, palaces, temples, and forts. The Taj Mahal, an epitome of architectural brilliance, stands as a symbol of Indias cultural and historical grandeur.Spirituality and philosophy have thrived in India for centuries. The birthplace of religions like Hinduism, Buddhism, Jainism, and Sikhism, India has been a sanctuary for seekers of spiritual en

Copy dataset to arrange audio and noise in different folders

In [5]:
!cp -r "C:/Users/bhava/surge_classes/SPEECH_PROJECTcustome_audio" ./

'cp' is not recognized as an internal or external command,
operable program or batch file.


In [6]:
data_directory = "C:/Users/bhava/surge_classes/SPEECH_PROJECT/custome_audio"
audio_folder = "audio"
noise_folder = "noise"

audio_path = os.path.join(data_directory, audio_folder)
noise_path = os.path.join(data_directory, noise_folder)

In [7]:
audio_path

'C:/Users/bhava/surge_classes/SPEECH_PROJECT/custome_audio\\audio'

In [8]:
valid_split = 0.1

shuffle_seed = 43

sample_rate = 22050

scale = 0.5

batch_size = 25

epochs = 10

In [9]:
for folder in os.listdir(data_directory):
    if os.path.isdir(os.path.join(data_directory, folder)):
        if folder in [audio_folder, noise_folder]:
            
            continue
        elif folder in ["other", "_background_noise_"]:
            
            shutil.move(
                os.path.join(data_directory, folder),
                os.path.join(noise_path, folder),
            )
        else:
            shutil.move(
                os.path.join(data_directory, folder),
                os.path.join(audio_path, folder),
            )

In [10]:
noise_paths = []
for subdir in os.listdir(noise_path):
    subdir_path = Path(noise_path) / subdir
    if os.path.isdir(subdir_path):
        noise_paths += [
            os.path.join(subdir_path, filepath)
            for filepath in os.listdir(subdir_path)
            if filepath.endswith(".wav")
        ]

In [11]:
noise_paths

['C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\other\\exercise_bike.wav',
 'C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\other\\pink_noise.wav',
 'C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\_background_noise_\\10convert.com_Audience-Claps_daSG5fwdA7o.wav',
 'C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\_background_noise_\\doing_the_dishes.wav',
 'C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\_background_noise_\\dude_miaowing.wav',
 'C:\\Users\\bhava\\surge_classes\\SPEECH_PROJECT\\custome_audio\\noise\\_background_noise_\\running_tap.wav']

In [12]:
command = (
    "for dir in `ls -1 " + noise_path + "`; do "
    "for file in `ls -1 " + noise_path + "/$dir/*.wav`; do "
    "sample_rate=`ffprobe -hide_banner -loglevel panic -show_streams "
    "$file | grep sample_rate | cut -f2 -d=`; "
    "if [ $sample_rate -ne 16000 ]; then "
    "ffmpeg -hide_banner -loglevel panic -y "
    "-i $file -ar 16000 temp.wav; "
    "mv temp.wav $file; "
    "fi; done; done"
)

In [13]:
os.system(command)
def load_noise_sample(path):
    sample, sampling_rate = tf.audio.decode_wav(
        tf.io.read_file(path), desired_channels=1
    )
    print(sampling_rate)
    if sampling_rate == sample_rate:
        slices = int(sample.shape[0] / sample_rate)
        sample = tf.split(sample[: slices * sample_rate], slices)
        return sample
    else:
        print("Sampling rate for",path, "is incorrect")
        return None


noises = []
for path in noise_paths:
    sample = load_noise_sample(path)
    if sample:
        noises.extend(sample)
noises = tf.stack(noises)

tf.Tensor(22050, shape=(), dtype=int32)
tf.Tensor(22050, shape=(), dtype=int32)
tf.Tensor(44100, shape=(), dtype=int32)
Sampling rate for C:\Users\bhava\surge_classes\SPEECH_PROJECT\custome_audio\noise\_background_noise_\10convert.com_Audience-Claps_daSG5fwdA7o.wav is incorrect
tf.Tensor(22050, shape=(), dtype=int32)
tf.Tensor(22050, shape=(), dtype=int32)
tf.Tensor(22050, shape=(), dtype=int32)


In [14]:
print(noises)

tf.Tensor(
[[[ 0.        ]
  [ 0.        ]
  [ 0.        ]
  ...
  [ 0.00152588]
  [ 0.0274353 ]
  [ 0.03463745]]

 [[ 0.02236938]
  [ 0.01980591]
  [ 0.03091431]
  ...
  [ 0.02532959]
  [-0.00656128]
  [ 0.00299072]]

 [[ 0.02719116]
  [ 0.01367188]
  [-0.01776123]
  ...
  [ 0.00491333]
  [ 0.02386475]
  [ 0.01412964]]

 ...

 [[-0.17727661]
  [-0.0687561 ]
  [ 0.03491211]
  ...
  [-0.06976318]
  [-0.09143066]
  [-0.0296936 ]]

 [[ 0.04153442]
  [ 0.02423096]
  [-0.00283813]
  ...
  [-0.09466553]
  [ 0.04885864]
  [ 0.06637573]]

 [[-0.06341553]
  [-0.02102661]
  [ 0.08428955]
  ...
  [-0.09603882]
  [ 0.03704834]
  [ 0.12103271]]], shape=(338, 22050, 1), dtype=float32)


In [15]:
def paths_and_labels_to_dataset(audio_paths, labels):
    path_ds = tf.data.Dataset.from_tensor_slices(audio_paths)
    audio_ds = path_ds.map(lambda x: path_to_audio(x))
    label_ds = tf.data.Dataset.from_tensor_slices(labels)
    return tf.data.Dataset.zip((audio_ds, label_ds))

In [16]:
def path_to_audio(path):
    audio = tf.io.read_file(path)
    audio, _ = tf.audio.decode_wav(audio, 1, sample_rate)
    return audio

In [17]:
def add_noise(audio, noises=None, scale=0.5):
    if noises is not None:
        tf_rnd = tf.random.uniform(
            (tf.shape(audio)[0],), 0, noises.shape[0], dtype=tf.int32
        )
        noise = tf.gather(noises, tf_rnd, axis=0)

        prop = tf.math.reduce_max(audio, axis=1) / tf.math.reduce_max(noise, axis=1)
        prop = tf.repeat(tf.expand_dims(prop, axis=1), tf.shape(audio)[1], axis=1)

        audio = audio + noise * prop * scale

    return audio

In [18]:
def audio_to_fft(audio):
    audio = tf.squeeze(audio, axis=-1)
    fft = tf.signal.fft(
        tf.cast(tf.complex(real=audio, imag=tf.zeros_like(audio)), tf.complex64)
    )
    fft = tf.expand_dims(fft, axis=-1)

    return tf.math.abs(fft[:, : (audio.shape[1] // 2), :])

In [19]:
class_names = os.listdir(audio_path)
print(class_names,)

audio_paths = []
labels = []
for label, name in enumerate(class_names):
    print("Speaker:",(name))
    dir_path = Path(audio_path) / name
    speaker_sample_paths = [
        os.path.join(dir_path, filepath)
        for filepath in os.listdir(dir_path)
        if filepath.endswith(".wav")
    ]
    audio_paths += speaker_sample_paths
    labels += [label] * len(speaker_sample_paths)

['alekhya', 'bhavani', 'joharika', 'keerthi', 'likitha', 'parvathi', 'sunanda']
Speaker: alekhya
Speaker: bhavani
Speaker: joharika
Speaker: keerthi
Speaker: likitha
Speaker: parvathi
Speaker: sunanda


In [20]:
# Shuffle to generate random data
rng = np.random.RandomState(shuffle_seed)
rng.shuffle(audio_paths)
rng = np.random.RandomState(shuffle_seed)
rng.shuffle(labels)

In [21]:
# Split into training and validation
num_val_samples = int(valid_split * len(audio_paths))
train_audio_paths = audio_paths[:-num_val_samples]
train_labels = labels[:-num_val_samples]


valid_audio_paths = audio_paths[-num_val_samples:]
valid_labels = labels[-num_val_samples:]

In [22]:
# Create datasets, one for training and the other for validation
train_ds = paths_and_labels_to_dataset(train_audio_paths, train_labels)
train_ds = train_ds.shuffle(buffer_size=batch_size * 8, seed=shuffle_seed).batch(
    batch_size
)

valid_ds = paths_and_labels_to_dataset(valid_audio_paths, valid_labels)
valid_ds = valid_ds.shuffle(buffer_size=32 * 8, seed=shuffle_seed).batch(32)

In [23]:
# Add noise to the training set
train_ds = train_ds.map(
    lambda x, y: (add_noise(x, noises, scale=scale), y),
    num_parallel_calls=tf.data.experimental.AUTOTUNE,
)

# Transform audio wave to the frequency domain using `audio_to_fft`
train_ds = train_ds.map(
    lambda x, y: (audio_to_fft(x), y), num_parallel_calls=tf.data.experimental.AUTOTUNE
)

train_ds = train_ds.prefetch(tf.data.experimental.AUTOTUNE)

valid_ds = valid_ds.map(
    lambda x, y: (audio_to_fft(x), y), num_parallel_calls=tf.data.experimental.AUTOTUNE
)
valid_ds = valid_ds.prefetch(tf.data.experimental.AUTOTUNE)

In [24]:
from tensorflow.keras.layers import Conv1D

In [25]:
def residual_block(x, filters, conv_num = 3, activation = "relu"):
    s = keras.layers.Conv1D(filters, 1, padding = "same")(x)
    
    for i in range(conv_num - 1):
        x = keras.layers.Conv1D(filters, 3, padding = "same")(x)
        x = keras.layers.Activation(activation)(x)
    
    x = keras.layers.Conv1D(filters, 3, padding = "same")(x)
    x = keras.layers.Add()([x, s])
    x = keras.layers.Activation(activation)(x)
    
    return keras.layers.MaxPool1D(pool_size = 2, strides = 2)(x)

def build_model(input_shape, num_classes):
    inputs = keras.layers.Input(shape = input_shape, name = "input")
    
    x = residual_block(inputs, 16, 2)
    x = residual_block(inputs, 32, 2)
    x = residual_block(inputs, 64, 3)
    x = residual_block(inputs, 128, 3)
    x = residual_block(inputs, 128, 3)
    x = keras.layers.AveragePooling1D(pool_size=3, strides=3)(x)
    x = keras.layers.Flatten()(x)
    x = keras.layers.Dense(256, activation="relu")(x)
    x = keras.layers.Dense(128, activation="relu")(x)
    
    outputs = keras.layers.Dense(num_classes, activation = "softmax", name = "output")(x)
    
    return keras.models.Model(inputs = inputs, outputs = outputs)

model = build_model((sample_rate // 2, 1), len(class_names))

model.summary()

model.compile(optimizer="Adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"]) 

model_save_filename = "model.h5"

earlystopping_cb = keras.callbacks.EarlyStopping(patience=10, restore_best_weights=True)

mdlcheckpoint_cb = keras.callbacks.ModelCheckpoint(model_save_filename, monitor="val_accuracy", save_best_only=True)

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input (InputLayer)             [(None, 11025, 1)]   0           []                               
                                                                                                  
 conv1d_15 (Conv1D)             (None, 11025, 128)   512         ['input[0][0]']                  
                                                                                                  
 activation_10 (Activation)     (None, 11025, 128)   0           ['conv1d_15[0][0]']              
                                                                                                  
 conv1d_16 (Conv1D)             (None, 11025, 128)   49280       ['activation_10[0][0]']          
                                                                                              

In [26]:
history = model.fit(
    train_ds,
    epochs=epochs,
    validation_data=valid_ds,
    callbacks=[earlystopping_cb, mdlcheckpoint_cb],
)

Epoch 1/10
26/26 [==============================] - 69s 3s/step - loss: 22.5500 - accuracy: 0.2365 - val_loss: 3.1786 - val_accuracy: 0.1857
Epoch 2/10
26/26 [==============================] - 80s 3s/step - loss: 1.3570 - accuracy: 0.4873 - val_loss: 1.6463 - val_accuracy: 0.5429
Epoch 3/10
26/26 [==============================] - 71s 3s/step - loss: 0.6352 - accuracy: 0.7698 - val_loss: 0.7161 - val_accuracy: 0.8000
Epoch 4/10
26/26 [==============================] - 74s 3s/step - loss: 0.4290 - accuracy: 0.8508 - val_loss: 0.6802 - val_accuracy: 0.8143
Epoch 5/10
26/26 [==============================] - 77s 3s/step - loss: 0.4243 - accuracy: 0.8556 - val_loss: 0.5999 - val_accuracy: 0.8571
Epoch 6/10
26/26 [==============================] - 73s 3s/step - loss: 0.2490 - accuracy: 0.9079 - val_loss: 0.4567 - val_accuracy: 0.8714
Epoch 7/10
26/26 [==============================] - 68s 3s/step - loss: 0.2290 - accuracy: 0.9079 - val_loss: 0.5118 - val_accuracy: 0.8429
Epoch 8/10
26/26 [=

In [27]:
print("Accuracy of model:",model.evaluate(valid_ds))

3/3 [==============================] - 3s 506ms/step - loss: 0.6807 - accuracy: 0.8000
Accuracy of model: [0.6807418465614319, 0.800000011920929]


In [28]:
SAMPLES_TO_DISPLAY =5

test_ds = paths_and_labels_to_dataset(valid_audio_paths, valid_labels)
test_ds = test_ds.shuffle(buffer_size=batch_size * 8, seed=shuffle_seed).batch(
    batch_size
)

test_ds = test_ds.map(lambda x, y: (add_noise(x, noises, scale=scale), y))

for audios, labels in test_ds.take(1):
    ffts = audio_to_fft(audios)
    y_pred = model.predict(ffts)
    rnd = np.random.randint(0, batch_size, SAMPLES_TO_DISPLAY)
    #print(rnd)
    audios = audios.numpy()[rnd, :, :]
    labels = labels.numpy()[rnd]
    y_pred = np.argmax(y_pred, axis=-1)[rnd]

    for index in range(SAMPLES_TO_DISPLAY):
        print(
            "Speaker:\33{} {}\33[0m\tPredicted:\33{} {}\33[0m".format(
                "[92m" if labels[index] == y_pred[index] else "[91m",
                class_names[labels[index]],
                "[92m" if labels[index] == y_pred[index] else "[91m",
                class_names[y_pred[index]],
            )
        )
        if labels[index] ==y_pred[index]:
            print("Welcome")
        else:
            print("Sorry")
        print("The speaker is" if labels[index] == y_pred[index] else "", class_names[y_pred[index]])

1/1 [==============================] - 1s 1s/step
Speaker: sunanda	Predicted: sunanda
Welcome
The speaker is sunanda
Speaker: bhavani	Predicted: bhavani
Welcome
The speaker is bhavani
Speaker: likitha	Predicted: likitha
Welcome
The speaker is likitha
Speaker: bhavani	Predicted: bhavani
Welcome
The speaker is bhavani
Speaker: bhavani	Predicted: bhavani
Welcome
The speaker is bhavani


In [29]:
def paths_to_dataset(audio_paths):
    path_ds = tf.data.Dataset.from_tensor_slices(audio_paths)
    return tf.data.Dataset.zip((path_ds))

def predict(path, labels):
    test = paths_and_labels_to_dataset(path, labels)


    test = test.shuffle(buffer_size=batch_size * 8, seed=shuffle_seed).batch(
    batch_size
    )
    test = test.prefetch(tf.data.experimental.AUTOTUNE)


    test = test.map(lambda x, y: (add_noise(x, noises, scale=scale), y))

    for audios, labels in test.take(1):
        ffts = audio_to_fft(audios)
        y_pred = model.predict(ffts)
        rnd = np.random.randint(0, 1, 1)
        audios = audios.numpy()[rnd, :]
        labels = labels.numpy()[rnd]
        y_pred = np.argmax(y_pred, axis=-1)[rnd]

    for index in range(1):
            print(
            "Speaker:\33{} {}\33[0m\tPredicted:\33{} {}\33[0m".format(
            "[92m",y_pred[index],
                "[92m", y_pred[index]
                )
            )
            
            print("Speaker Predicted:",class_names[y_pred[index]])

In [ ]:
create_folder('test')

In [30]:
for i in range(30,35):
    #duration = 2  # Duration of audio recording in seconds
    #sample_rate = 44100  # Sample rate of audio recording
    #channels = 2
    #filename = 'test/input'+str(i+1)+'.wav'  # Output file name
    record_audio(duration=2,sample_rate=44100, channels=2, filename='test/input'+str(i+1)+'.wav')

In [31]:
path = ["C:/Users/bhava/surge_classes/SPEECH_PROJECT/test/input1.wav"]
try:
    predict(path, labels)
except:
    print("Error! Check if the file correctly passed or not!")

1/1 [==============================] - 0s 183ms/step
Speaker: 2	Predicted: 2
Speaker Predicted: joharika
